external:
  open-meteo-air-quality:
    url: https://air-quality-api.open-meteo.com
  open-meteo-geocoding:
    url: https://geocoding-api.open-meteo.com
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:29092
      value-serializer: org.apache.kafka.common.serialization.StringSerializer