external:
  open-meteo-air-quality:
    url: https://air-quality-api.open-meteo.com
  open-meteo-geocoding:
    url: https://geocoding-api.open-meteo.com
  open-meteo-weather-forecast:
    url: https://api.open-meteo.com
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

export:
  enable: true
  cron: "0 0/1 * * * *"